name = "HydrologyPlanetesimals"
uuid = "0f588840-2752-41b6-aea8-a336b7e3b19f"
authors = ["Beat Hubmann"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
